# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    #parameter_name: value
    my_admin_bundle.menu_listener.class: AppBundle\EventListener\MyMenuItemListListener

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\EventListener\SetupKnpMenuListener:
          tags:
              - { name: kernel.event_listener, event: theme.sidebar_setup_knp_menu, method: onSetupMenu }

    AppBundle\EventListener\AuthenticationListener:
        tags:
            - { name: kernel.event_listener, event: security.interactive_login , method: onSuccess }